export interface ProductData {
    id: string;
    category: string;
    type: string;
    name: string;
    gender: string;
    new: boolean;
    sale: boolean;
    rate: number;
    price: number;
    originPrice: number;
    brand: string;
    sold: number;
    quantity: number;
    quantityPurchase: number;
    sizes: string[];
    luxury: boolean;
    variation: {
        color: string;
        colorCode: string;
        colorImage: string;
        image: string;
        material: string;
    }[];
    thumbImage: string[];
    images: string[];
    description: string;
    action: string;
    slug: string;
};
